# Site settings
title: Anant Alok
description: 'Website to showcase my work.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/anant-alok" # the subpath of your site, e.g. /blog
url: "https://anant-alok.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Anant Alok # add your name
author-pic: Myself_Neon_grey.jpg
about-author: I completed my Bachelor of Engineering in Mechanical Engineering from BMS College of Engineering. With 4.5 years of professional experience as a Data Analyst, I have developed a strong analytical and problem-solving skill set. Currently, I am pursuing a Master of Science in Industrial Engineering and Management, specializing in Supply Chain and Logistics. My passion lies in leveraging optimization tools and conducting research to enhance efficiency and innovation in supply chain systems.

# Contact links
email: iamanantalok@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://anant-alok.github.io # Add your website
linkedin: Anant Alok # Add your Linkedin handle
github: iamanantalok # Add your Github handle




# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: @disqus_M57PMEHAOI # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
